# Generated by Django 4.2.7 on 2024-08-13 14:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('source_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_currency', models.CharField(max_length=20)),
                ('source_country', models.CharField(max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_currency', models.CharField(max_length=20)),
                ('target_country', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Deleted', 'Deleted')], default='Draft', max_length=20)),
                ('concept', models.CharField(blank=True, max_length=255, null=True)),
                ('rate_exchange', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('sender_full_name', models.CharField(default='', max_length=255)),
                ('receiver_full_name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
