# Generated by Django 4.2.7 on 2025-01-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source_country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source_currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Deleted', 'Deleted')], default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='target_country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='target_currency',
            field=models.CharField(max_length=3),
        ),
    ]
